### PR TITLE
changes to add device in envsetup.sh

### PR DESCRIPTION
**Pull request by cobalt9**
Change-Id: Ia5de78f00b6c72cef2568bd4888798504010b653

### CODE REVIEW

**Comment by HridayHS** [comment]
This isn't really needed. You can directly use command "brunch land" to make rom or to fetch land configurations "breakfast land" in lineageos.

**Comment by cobalt9** [comment]
ok.. thanks

**Comment by cobalt9** [comment]
yeah that's why i closed it.

**Comment by cobalt9** [comment]
sorry for wasting your time.
I did it for myself. I clicked on pull request by mistake.

**Comment by HridayHS** [comment]
No problem.

**Comment by cobalt9** [comment]
keep up good work 
thanks

**Pull request closed without merging**
